### ISSUE TITLE
Swift Tutorial - Unable to add message via console

### ISSUE THREAD

**Issue by ulukaya** [firebase/friendlychat-ios#1]
Test Message Sync section, When I add a message from console, it doesn't update the application UI. Also, it's not clear as to necessary steps for performing this action.

**Comment by kroikie** [comment]
@conradwt You have two options for adding a message, you can download the database and edit the JSON locally on your machine, or you can add the message nodes via the console. You must add the nodes in the same format as the existing ones for them to show up in your app.
