### ISSUE TITLE
What is responsible for data populating from firebase? 

### ISSUE THREAD

**Issue by goribchat** [firebase/friendlychat-ios#10]
When i add data on firebase manually, it is getting reflected on simulator. please tell me which method is responsible for this action?

**Comment by samtstern** [comment]
@goribchat can you explain your question further?  Is something not working, or are you just curious how Firebase Realtime Database works?

**Comment by goribchat** [comment]
@samtstern : I have started using codelab for data populating. In that particular project when i manually save data in firebase it is getting reflected on simulator. but when i done that same change on my particular piece of code, the data is not getting reflected on simulator? Can you help me regarding this matter.

**Comment by goribchat** [comment]
Thanks for the explanation sir. i have done it successfully.

**Comment by morganchen12** [comment]
Feel free to comment here if you have any more questions.

**Comment by goribchat** [comment]
no sir, it's done.
