### ISSUE TITLE
Error: Use of unresolved identifier 'showAlert'

### ISSUE THREAD

**Issue by grehce** [firebase/friendlychat-ios#16]
In Receive Reengagement Notifications [Optional], showAlert(withUserInfo: userInfo) throws the above error.

**Comment by morganchen12** [comment]
This is kind of a wart in the codelab. The `showAlert(withUserInfo:)` method is added later on in the same step you're describing, but it's kind of awkward that it's used before it's defined.

**Comment by ulukaya** [comment]
We've republished with updates.
