### ISSUE TITLE
pod setup id required before pod update

### ISSUE THREAD

**Issue by ShahnazK** [firebase/friendlychat-ios#20]
On Step#3 **Build the starter app** , point #2 you have mentioned to run `pod update`. But if we run that we get errors `[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`.
To resolve this error, `pod setup` is needed. If possible please mention into this tutorial.

**Comment by morganchen12** [comment]
This is only true for fresh CocoaPods installations, and is unnecessary for people who have used CocoaPods in other projects.

It's more suitable as part of the CocoaPods installation docs than it is as part of the codelab.

**Comment by ulukaya** [comment]
Updated to use "pod install" in FC and App Quality codelabs. Since repo gardener updates Podfile.lock we should always get the latest. I'll update FriendlyEats as well once I set up travis and repo gardener for it.
