### ISSUE TITLE
Small typo within the tutorial

### ISSUE THREAD

**Issue by starkindustries** [firebase/friendlychat-ios#22]
In the Firebase iOS Swift FriendlyChat tutorial, there is a small typo. It is under **Step 8: Store and Receive Images** > **Receive images in existing messages** in the `FCViewController.swift` code. In this line:
`    if let imageURL = message[Constants.MessageFields.imageURR] {`
`imageURR` should be `imageURL`.

Link to Step 8: 
https://codelabs.developers.google.com/codelabs/firebase-ios-swift/#7

**Comment by starkindustries** [comment]
if let imageURL = message[Constants.MessageFields.imageURR] {

**Comment by ulukaya** [comment]
fixed. thanks!
