### ISSUE TITLE
Starter app not working, with error 'You must specify |clientID| for |GIDSignIn|'

### ISSUE THREAD

**Issue by amchew** [firebase/friendlychat-ios#38]
Hello @morganchen12 and @ulukaya !

This is a continuation of https://github.com/firebase/friendlychat-web/issues/156.

I am doing the Firebase authentication tutorial here: https://codelabs.developers.google.com/codelabs/firebase-ios-swift/#4

I see the error:
```
FriendlyChatSwift[5221:437165] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'You must specify |clientID| for |GIDSignIn|'
```

I read the messages in #156 and inserted the code
```
func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
        FirebaseApp.configure();
        GIDSignIn.sharedInstance().clientID = FirebaseApp.app()?.options.clientID
        return true
    }
```
in the AppDelegate.swift file, but still see the error.

Would you know why?

**Comment by morganchen12** [comment]
Can you share your GoogleService-Info.plist file, with keys redacted?

**Comment by amchew** [comment]
@morganchen12 Yes! Please see:
![image](https://user-images.githubusercontent.com/33160470/50193701-8cd7c880-02ec-11e9-864f-9f012b34c378.png)

**Comment by amchew** [comment]
Hi @morganchen12 and @ulukaya, please see above ^ !

**Comment by morganchen12** [comment]
@amchew can you upload your project in its current state to a git repo so I can poke around? There's nothing wrong with your GoogleService-Info.plist file.

**Comment by amchew** [comment]
@morganchen12 Yup! Here is the repo: https://github.com/amchew/friendlychat-ios

**Comment by amchew** [comment]
Hey @morganchen12 ! I ran `pods update` and ran my build again and still see the error:
```FriendlyChatSwift[3285:112147] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'You must specify |clientID| for |GIDSignIn|'``` unfortunately.

**Comment by morganchen12** [comment]
It turns out this (probably) wasn't pods-related. There's a curly-brace error in your project, so your `application(_:didFinishLaunchingWithOptions:)` method isn't being called. Here's the diff to fix your code:

```diff
         print("Error \(error)")
         return
       }
+    }
   }
     
   func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplicationLaunchOptionsKey: Any]?) -> Bool {
     FirebaseApp.configure()
-    GIDSignIn.sharedInstance().clientID = FirebaseApp.app()?.options.clientID
-    //GIDSignIn.sharedInstance().delegate = self
     return true
   }
 }
-}
```

Running pod update doesn't actually update your pods because we set the project platform version to iOS 7, which is unnecessary. I'll fix that.

Thanks for reporting!
