### ISSUE TITLE
Crashlytics instructions not working

### ISSUE THREAD

**Issue by amchew** [firebase/friendlychat-ios#39]
Hi @morganchen12 and @ulukaya ! I'm on step 14 of the tutorial (https://codelabs.developers.google.com/codelabs/firebase-ios-objc/#13), under the header `nitiate crash`. When I insert the code
```
- (IBAction)didPressCrash:(id)sender {
  [[Crashlytics sharedInstance] crash];
}
```
in my `FCViewController.m` file, I see this error:

![image](https://user-images.githubusercontent.com/33160470/50238526-7a08d680-0374-11e9-8f3b-ffffc3fc78e8.png)

Would you know why?

**Comment by morganchen12** [comment]
That line of code deliberately invokes a crash. The error you're seeing is the debugger stopping on the line of code that crashed. In Xcode, click `Debug > Detach` from the dropdown menu at the top of the screen and the debugger will detach from your app, allowing the simulator to continue execution after the crash.

The codelab instructions tell you to end the debug run and then open it from the simulator, which achieves the same purpose. Let me know if you feel the instructions here were unclear, and I'll update the codelab.

Thanks for all your feedback!

**Comment by amchew** [comment]
Hi @morganchen12 ! 
Got it. So I am at Step 5 of https://codelabs.developers.google.com/codelabs/firebase-ios-objc/#13: 
![image](https://user-images.githubusercontent.com/33160470/50256483-5c0a9880-03ab-11e9-836a-2e07b79920c0.png)

I then go to the Firebase portal and see: 
![image](https://user-images.githubusercontent.com/33160470/50256492-6331a680-03ab-11e9-8d4c-be4b21b44c7f.png)

I clicked `Link app in Fabric` and I see:

![image](https://user-images.githubusercontent.com/33160470/50256505-70e72c00-03ab-11e9-83e7-e0294f07a89a.png)

Would you know why?

**Comment by morganchen12** [comment]
Did you answer `no` to the `Is your app new to Crashlytics` question?

**Comment by amchew** [comment]
Yup!

**Comment by morganchen12** [comment]
That's a super confusing part of our Crashlytics UI, and answering `No` is supposed to mean you already had Crashlytics integrated into your app via Fabric before moving to Firebase, not that your app already had the Crashlytics (via Firebase) SDK installed.

@TKBurner we should do something about that, this isn't the first time someone's been confused by this UI and there's no undo button in this case.

@amchew if you'd like to get someone to unstick your project you can [file a support ticket](https://firebase.google.com/support/contact/?category=troubleshooting).

**Comment by amchew** [comment]
Thanks @morganchen12 ! Yes I filed a support ticket. 
The experience connecting Firebase with Crashlytics isn't very good, the UI is different and the instructions may not be so clear. But the support (@morganchen12) has been great, so kudos!
