### ISSUE TITLE
When I attempt to run FriendlyChatSwift, six Buildtime errors cause the build to fail

### ISSUE THREAD

**Issue by aGhostyBabe** [firebase/friendlychat-ios#4]
![screen shot 2017-08-14 at 5 57 30 pm](https://user-images.githubusercontent.com/30996265/29293750-31c20c4e-811a-11e7-95d0-3cc373d071bc.png)

Screenshots attached. The error reads: "Apple Mach-O Linker Error"

As a relative amateur, I have been unable to solve this issue in order to complete the codelabs and learn how to use FireBase.

**Comment by morganchen12** [comment]
I'm unable to reproduce these errors. What versions of CocoaPods/Xcode are you using?

**Comment by kroikie** [comment]
@aGhostyBabe is this still an issue for you.

**Comment by kroikie** [comment]
@aGhostyBabe closing this issue, please reopen or file another one if you still have this issue.
