### ISSUE TITLE
Getting 2 Errors on Step 4.

### ISSUE THREAD

**Issue by shingetzu** [firebase/friendlychat-ios#7]
I'm copying the code listed but I'm getting these errors when I run it.

1. Type 'AppDelegate' does not conform to protocol 'GIDSignInDelegate'
2. Invalid redeclaration of 'sign(_:didSignInFor:withError:)'

**Comment by morganchen12** [comment]
You've defined the `sign(_:didSignInFor:withError:)` method twice. Remove one of them and your errors should go away.

**Comment by consbulaquena** [comment]
@morganchen12 Thanks! IT solved my  redeclaration error.
