### ISSUE TITLE
Step 5 can't Login use google account. 

### ISSUE THREAD

**Issue by legolasW** [firebase/friendlychat-ios#77]
Error 403: restricted_client

This app is not configured to make OAuth request.

I'm not sure why, I already enabled Google Login in firebase console

**Comment by anguszzzz** [comment]
Same issue, have you found any solutions for it?

**Comment by legolasW** [comment]
Sadly I don't have any solution for it. I implemented firebaseUI instead. But I'm still interested in the solution of this.

**Comment by G-Wizz** [comment]
I have the same issue. Unable to locate a solution for it.

**Comment by morganchen12** [comment]
See this similar JS quickstart issue. https://github.com/firebase/quickstart-js/issues/324

**Comment by tpetrovits** [comment]
I had the same issue and finally, I stumble on Application logo. When I add this, the problem was solved.
