### ISSUE TITLE
Make iOS and Android FriendlyChat compatible

### ISSUE THREAD

**Issue by madmax330** [firebase/friendlychat-ios#9]
It would be nice to have the Android and iOS Friendly chat application be compatible. For that the database field references for the friendly message need to change from "imageURL" to "imageUrl" and "photoURL" to "photoUrl" (making the 'r' and 'l' lowercase). 
That way people who completed both tutorials can "chat" on the tutorial applications from each platform respectively, whereas without these changes the iOS app cannot load the android images, and the android app crashed trying to load the iOS image messages.

Here is the code that needs to be changed, pretty simple: 

**Constants.swift**
Replace
`struct MessageFields {
    static let name = "name"
    static let text = "text"
    static let photoURL = "photoURL"
    static let imageURL = "imageURL"
  }`

With 
`struct MessageFields {
    static let name = "name"
    static let text = "text"
    static let photoUrl = "photoUrl"
    static let imageUrl = "imageUrl"
  }`

**FCViewController.swift**
Replace
`if let imageURL = message[Constants.MessageFields.imageURL] {` (161)

`if let photoURL = message[Constants.MessageFields.photoURL], let URL = URL(string: photoURL),` (181)

`if let photoURL = Auth.auth().currentUser?.photoURL {
            mdata[Constants.MessageFields.photoURL] = photoURL.absoluteString
        }` (202-204)

`strongSelf.sendMessage(withData: [Constants.MessageFields.imageURL: strongSelf.storageRef.child((metadata?.path)!).description])` (244)

`strongSelf.sendMessage(withData: [Constants.MessageFields.imageURL: strongSelf.storageRef.child((metadata?.path)!).description])` (260)

With
`if let imageURL = message[Constants.MessageFields.imageUrl] {`(161)

`if let photoUrl = message[Constants.MessageFields.photoUrl], let URL = URL(string: photoUrl),`(181)

`if let photoUrl = Auth.auth().currentUser?.photoURL {
            mdata[Constants.MessageFields.photoUrl] = photoUrl.absoluteString
        }`(202-204)

`strongSelf.sendMessage(withData: [Constants.MessageFields.imageUrl: strongSelf.storageRef.child((metadata?.path)!).description])` (244)

`strongSelf.sendMessage(withData: [Constants.MessageFields.imageUrl: strongSelf.storageRef.child((metadata?.path)!).description])` (260)

**Comment by asdfghj1237890** [comment]
@madmax330 thank you for your implement, i am just finding the reason of this issue for a whole day.
It would be very nice for the people who would like to make applications on both ios and android.

**Comment by samtstern** [comment]
@madmax330 thanks for raising this!  We definitely intended these apps to be compatible, looks like our database schemas drifted over time.

@morganchen12 or @ulukaya can you handle this one?

**Comment by ulukaya** [comment]
I'll fix this.

**Comment by ulukaya** [comment]
https://github.com/firebase/friendlychat-ios/commit/f3125cd0816171d0dcf581d0a956d29a245a9376

**Comment by ulukaya** [comment]
Actually reverted constant naming, just changed the strings. Looks like iOS prefers "URL" vs Android prefers "Url". Just using "Url" in database should be enough for them to cooperate.
https://github.com/firebase/friendlychat-ios/commit/7c4694c9155227d20a907840592369d7370c2c7b
